//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _WindowsFormIslemleri_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelGirisTablosu
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string MailAdress { get; set; }
        public string Password { get; set; }
    }
}
